import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    en:{
	lang:"Language",
	
	Home:"Home",
	Tournaments:"Tournaments",
	Tournament:"Tournament",
	Games:"Games",
	Feed:"Feed",
	Auth:"Auth",
	
	New: "New",
	Create: "Create",
	Login: "Login",
	Logout: "Logout",
	Password: "Password",
	Register: "Register",
	Status: "Status",
	DeleteAccount: "Delete account",
	Hello: "Hello",

	Description: "Description",
	Title: "Title",
	Game: "Game",
	At: "At",
	Reward: "Reward",

	All: "all",
	Registered: "Registered",
	Created: "Created",
	Dashboard: "Dashboard",

	Promote: "Promote",
	Delete: "Delete",
	Edit: "Edit",
	Select: "Select",
	Unselect: "Unselect",
	Unregister: "Unregister",
	Announce: "Announce",
	Author: "Author",
	Text: "Text",
	SelectedTournament: "Selected tournament",
	NotSelectedTournament: "No tournament selected",

	Question: "Question",
	Questions: "Questions",
	Save: "Save",
	RegisteredUsers: "Registered users",
	NoRegisteredUsers: "No registered users",
	Pending: "Pending",
	Asked: "Asked",
	NotAnsweredYet: "Ще немає відповіді",
	asking: "asking",
	Answer: "Answer"
    },
    ru: {
	lang:"Язык",
	Home:"Главная",
	Tournaments:"Турниры",
	Tournament:"Турнир",
	Games:"Игры",
	Feed:"Лента",
	Auth:"Авторизация",

	New: "Создать",
	Create: "Создать",
	Login: "Войти в аккаунт",
	Logout: "Выйти из аккаунта",
	Password: "Пароль",
	Register: "Зарегистрироваться",
	Status: "Статус",
	DeleteAccount: "Удалить аккаунт",
	Hello: "Привет",

	Description: "Описание",
	Title: "Название",
	Game: "Игра",
	At: "Время",
	Reward: "Награда",

	All: "Все",
	Registered: "Зарегистрированные",
	Created: "Созданные",
	Dashboard: "Панель",

	Promote: "Поднять",
	Delete: "Удалить",
	Edit: "Изменить",
	Select: "Выбрать",
	Unselect: "Снять выбор",
	Unregister: "Отменить регистрацию",
	Announce: "Объявление",
	Author: "Автор",
	Text: "Текст",
	SelectedTournament: "Выбран турнир",
	NotSelectedTournament: "Нет выбранного турнира",

	Question: "Вопрос",
	Questions: "Вопросы",
	Save: "Сохранить",
	RegisteredUsers: "Зарегистрированные пользователи",
	NoRegisteredUsers: "Никто не зарегистрировался",
	Pending: "Ожидающие ответа",
	Asked: "Спрошенные",
	NotAnsweredYet: "Ще немає відповіді",
	asking: "вопрошает",
	Answer: "Ответ"
    },
    uk: {
	lang:"Мова",
	Home:"Головна",
	Tournaments:"Турнiри",
	Tournament:"Турнiр",
	Games:"Iгри",
	Feed:"Лента",
	Auth:"Авторизацiя",

	New: "Додати",
	Create: "Створити",
	Login: "Увійти",
	Logout: "Вихід із системи",
	Password: "Пароль",
	Register: "Реєстрація",
	Status: "Статус",
	DeleteAccount: "Видалити обліковий запис",
	Hello: "Привіт",

	Description: "Опис",
	Title: "Назва",
	Game: "Гра",
	At: "Час",
	Reward: "Нагорода",

	All: "Усі",
	Registered: "Зареєстровано",
	Created: "Створено",
	Dashboard: "Панель",

	Promote: "Пiдняти",
	Delete: "Видалити",
	Edit: "Змiнити",
	Select: "Вибрати",
	Unselect: "Зняти вибiр",
	Unregister: "Скасувати реєстрацiю",
	Announce: "Оголошення",
	Author: "Автор",
	Text: "Текст",
	SelectedTournament: "Обрано турнiр",
	NotSelectedTournament: "Немає обраного турнiру",

	Question: "Питання",
	Questions: "Питання",
	Save: "Зберегти",
	RegisteredUsers: "Зареєстровані користувачі",
	NoRegisteredUsers: "Зареєстрованих немає",
	Pending: "Очікуючі",
	Asked: "Спитані",
	NotAnsweredYet: "Ще немає відповіді",
	asking: "питає",
	Answer: "Відповідь"
    }
});

export default strings;
